feat: quiz backend part completed
Jaynil1611/Dietify-Quiz pull request #4
Opened 2021-06-02 12:35 UTC by Jaynil1611

- [Quiz Backend Live](https://dietify-quiz-backend.vercel.app/)

2021-06-04 14:53 UTC, Aravindan07 requested changes
Great work Jaynil with the quiz app. I have included some minor changes.

2021-06-04 14:53 UTC, Aravindan07 commented on backend/package.json
> +    "body-parser": "^1.19.0",
You don't need to install body-parser separately it is pre-built in the express package.

2021-06-04 14:53 UTC, Aravindan07 commented on backend/controllers/login.controller.js
> +      .json({ success: false, errorMessage: "Passwords don't match" });
These error messages are not consumed by the UI I guess. You are showing hard-coded error messages why not use these messages. Not a backend fix though, just mentioning the issue.

2021-06-04 14:53 UTC, Aravindan07 commented on backend/controllers/login.controller.js
> +        },
Why you created a separate file for login when you already have a user.controller.js file. You put the logic of signup there why not login too?

2021-06-04 14:53 UTC, Aravindan07 commented on backend/middlewares/paramHandler.js
> +      message: "Couldn't retrieve the quiz",
Couldn't retrieve the quiz sounds like a server issue. If it is then change the status code to 5XX.

2021-06-04 14:53 UTC, Aravindan07 commented on backend/middlewares/paramHandler.js
> +    });
Same here too check the status code

2021-06-04 14:53 UTC, Aravindan07 commented on backend/controllers/quizAttempt.controller.js
> +  res.status(201).json({ success: true, quizzes });
It's a get request so the status code will be 200.

2021-06-04 14:53 UTC, Aravindan07 commented on backend/controllers/quizAttempt.controller.js
> +    console.log({ quiz });
Remove logs

2021-06-04 14:53 UTC, Aravindan07 commented on backend/utils/createUser.js
> +//userId: 60ae411072e44c2e44da4814
remove comments

2021-06-04 14:53 UTC, Aravindan07 commented on backend/utils/createUser.js
> +//userId: 60ae411072e44c2e44da4814
You are not using this function I think. If you are not using then remove it.

2021-06-09 18:31 UTC, aneenajohn requested changes
Good work, Jaynil!
Its a pleasure to look through such well structured code. I had suggested some minor changes

2022-09-02 18:03 UTC, merged